### ISSUE TITLE
Results Question

### ISSUE THREAD

**Issue by minyaho** [HITSZ-HLT/JointCL#4]
Hi, I also have the same question. I can't reproduce the result. I tried your code with the same version of python libraries and  hyperparameters which in the code, but the result was bad. I use the twitter_testDT_seenval dataset and the result is shown in the image below.

![image](https://user-images.githubusercontent.com/54090504/191689007-d2d53c2c-a257-4d6f-8d4a-b07a1bc8dd1a.png)
![image](https://user-images.githubusercontent.com/54090504/191689045-7fd69c7a-4e6d-4d63-b165-ba5f6fc0fae4.png)

**Comment by MatchaLove** [comment]
I tried the code，and I also cannot reproduce the result. This is the result.
![1664443236656](https://user-images.githubusercontent.com/62493195/192993915-f0a814de-6bdd-4de7-827d-161fc02b78d3.png)

**Comment by Wenze7** [comment]
> I tried the code，and I also cannot reproduce the result. This is the result. ![1664443236656](https://user-images.githubusercontent.com/62493195/192993915-f0a814de-6bdd-4de7-827d-161fc02b78d3.png)

Hi, bro, have you tried this project in VAST? Can you reproduce the result in VAST?

**Comment by BinLiang-NLP** [comment]
Sorry for the inconvenience. I am checking the code and will reply to you asap. Many Thanks!

**Comment by BinLiang-NLP** [comment]
> Hi, I also have the same question. I can't reproduce the result. I tried your code with the same version of python libraries and hyperparameters which in the code, but the result was bad. I use the twitter_testDT_seenval dataset and the result is shown in the image below.
> 
> ![image](https://user-images.githubusercontent.com/54090504/191689007-d2d53c2c-a257-4d6f-8d4a-b07a1bc8dd1a.png) ![image](https://user-images.githubusercontent.com/54090504/191689045-7fd69c7a-4e6d-4d63-b165-ba5f6fc0fae4.png)

Hi, I have checked the code, and I found that the results of some targets are OK, such as HC, LA, and A.
I am still checking the code of DT and CC to find the reason for the performance difference. Please wait a few days. Thanks a lot.

**Comment by BinLiang-NLP** [comment]
> I tried the code，and I also cannot reproduce the result. This is the result. ![1664443236656](https://user-images.githubusercontent.com/62493195/192993915-f0a814de-6bdd-4de7-827d-161fc02b78d3.png)

Hi, I have checked the code, and I found that the results of some targets are OK, such as HC, LA, and A.
I am still checking the code of DT and CC to find the reason for the performance difference. Please wait a few days. Thanks a lot.

**Comment by BinLiang-NLP** [comment]
> Hi, I also have the same question. I can't reproduce the result. I tried your code with the same version of python libraries and hyperparameters which in the code, but the result was bad. I use the twitter_testDT_seenval dataset and the result is shown in the image below.
> 
> ![image](https://user-images.githubusercontent.com/54090504/191689007-d2d53c2c-a257-4d6f-8d4a-b07a1bc8dd1a.png) ![image](https://user-images.githubusercontent.com/54090504/191689045-7fd69c7a-4e6d-4d63-b165-ba5f6fc0fae4.png)


Hi, sorry again for the inconvenience.
We have fixed the problems. Please run "_git pull_" to update the code.
We found that due to the small number of dataset samples (especially SEM16), the performance gap between different seeds will vary greatly. Thus, please tune the parameter "_--seed_" for better performance, no other parameter tuning is required.
Please let me know if there is any problem.
Thanks a lot!!!

**Comment by BinLiang-NLP** [comment]
> I tried the code，and I also cannot reproduce the result. This is the result. ![1664443236656](https://user-images.githubusercontent.com/62493195/192993915-f0a814de-6bdd-4de7-827d-161fc02b78d3.png)

Hi, I apologize for the inconvenience.
We have fixed the problems. Please run "_git pull_" to update the code.
We found that due to the small number of dataset samples (especially SEM16), the performance gap between different seeds will vary greatly. Thus, please tune the parameter "--seed" for better performance, no other parameter tuning is required.
Please let me know if there is any problem.
Thanks a lot!!!
